apiVersion: v1
kind: Service
metadata:
  name: my-demo-service
  labels:
    app: my-demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo1
  ports:
  - name: http
    port: 80
    targetPort: 8080