apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo4
  annotations:
    kubernetes.io/change-cause: "Initial deploy"
spec:
  # -----
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  # -----
  replicas: 3
  template:
    metadata:
      labels:
        app: demo4
    spec:
      containers:
      - name: my-demo-app
        image: eu.gcr.io/delta-n-k8s-kennissessie/demo4:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # -----
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
        # -----

